#!/usr/bin/env bash

source ./scripts/libs/common
source ./scripts/libs/osx

main() {
  config_sudo
  setup_osx_gui
  install_homebrew
  brew_install_with_requirement ./requirements/brew/base/formulae.txt
  brew_install_with_requirement ./requirements/brew/base/cask.txt
  install_vscode_ext
  config_zsh
  config_git
  config_iterm2
  config_autojump
  config_apps
  mac_app_store_install_applications ./requirements/mac-app-store/base.txt
}

main
