#!/usr/bin/env bash

set -euo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

# shellcheck source=../../../libs/osx
source "$(dirname "${BASH_SOURCE[0]}")/../../../libs/osx"

main() {
  config_sudo
  setup_osx_gui
  install_homebrew
  brew_install_with_requirement "${DOTFILES_DIR}/requirements/brew/base/formulae.txt"
  brew_install_with_requirement "${DOTFILES_DIR}/requirements/brew/base/cask.txt" --cask
  config_zsh
  install_vscode_ext
  config_git
  config_iterm2
  config_apps
  mac_app_store_install_applications "${DOTFILES_DIR}/requirements/mac-app-store/base.txt"
}

main
