#!/usr/bin/env bash

set -euo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

# shellcheck source=../../../libs/osx
source "$(dirname "${BASH_SOURCE[0]}")/../../../libs/osx"

main() {
  config_sudo
  config_apps
}

main
