#!/usr/bin/env bash

source ./scripts/libs/common
source ./scripts/libs/osx

main() {
  install_xcode
  brew_install_with_requirement ./requirements/brew/developer/fullstack/formulae.txt
  install_pyenv
  install_python
  install_nvm
  install_node
  install_gvm
  install_go
  install_vscode_ext
  brew_install_with_requirement ./requirements/brew/developer/fullstack/cask.txt
}

main
