#!/usr/bin/env bash

set -euo pipefail
[[ -n "${DEBUG:-}" ]] && set -x

# shellcheck source=../../../libs/osx
source "$(dirname "${BASH_SOURCE[0]}")/../../../libs/osx"

main() {
  install_xcode
  brew_install_with_requirement "${DOTFILES_DIR}/requirements/brew/developer/fullstack/formulae.txt"
  brew_install_with_requirement "${DOTFILES_DIR}/requirements/brew/developer/fullstack/cask.txt" --cask
  install_pyenv
  install_python
  install_nvm
  install_node
  install_gvm
  install_go
  install_vscode_ext
  install_kubectl
  install_session_manager_plugin
  config_ecr_credential_helper
}

main
